name: Deploy Next.js

on:
  push:
    branches:
      - development # Change to your deployment branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.1.0'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: 22 # Change if your SSH port is different
          DEPLOY_PATH: /home/ozfea/public_html/nrk-next # Change to your actual deployment path
        run: |
          # Setup SSH Key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Sync files
          rsync -avz -e "ssh -p $SSH_PORT" --delete ./.next/ $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH

          # Optional: Any post-deployment steps
          # ssh -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "cd $DEPLOY_PATH && any-post-deployment-command"
