# name: Deploy Next.js

# on:
#   push:
#     branches:
#       - development # Change to your deployment branch if different

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '19.1.0'

#       - name: Install dependencies
#         run: npm install

#       - name: Build the application
#         run: npm run build

#       - name: Install rsync
#         run: |
#           sudo apt-get update && sudo apt-get install -y rsync
#           rsync --version

#       - name: Deploy to server
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SSH_HOST: ${{ secrets.SSH_HOST }}
#           SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
#           SSH_PORT: 22
#           DEPLOY_PATH: /home/ozfea/public_html/nrk-next
#         run: |
#           mkdir -p ~/.ssh
#           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
#           chmod 644 ~/.ssh/known_hosts

#           # Sync files
#           rsync -avz -e "ssh -p $SSH_PORT" --delete ./.next/ $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH

name: Deploy Next.js to cPanel

on:
  push:
    branches:
      - development # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to cPanel
        env:
          CPANEL_HOST: ${{ secrets.SSH_HOST }}
          CPANEL_PORT: 22
          CPANEL_USER: ${{ secrets.SSH_USERNAME }}
          CPANEL_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Optional: Add SSH key if using key-based authentication
          echo "$CPANEL_KEY" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key

          # Deploy files to cPanel
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p $CPANEL_PORT" \
            --exclude=node_modules --exclude=.next --exclude=.git \
            ./ $CPANEL_USER@$CPANEL_HOST:/home/ozfea/public_html/nrk-next

          # Cleanup
          ssh-agent -k
          rm private_key
